pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                echo 'Building project...' 
                bat "ant build-and-publish"
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'build/newArtifacts/*', fingerprint: true
        }
    }
}