pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                echo 'Building project...' 
                bat "ant build-and-deploy"
            }
        }
    }
}